# Generated by Django 3.1.13 on 2021-10-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('family_name', models.CharField(max_length=40, verbose_name='Sobrenome')),
                ('birthday', models.DateField(verbose_name='Aniversário')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Feminino'), (1, 'Masculino'), (3, 'Outro'), (4, 'Prefiro não dizer')], default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Ativo'), (1, 'Inativo'), (2, 'Cancelado'), (3, 'Transferido')], default=0)),
                ('student_id', models.CharField(max_length=40, verbose_name='RA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
